var number1 = 5;
var number2 = 10;
console.log("Is number 1 < number 2? I predict True!");
console.log(number1 < number2);
var fruit1 = "Mango";
var fruit2 = "Mango";
console.log("Is fruit 1 same as fruit 2? I predict True!");
console.log(fruit1 == fruit2);
var firstPencilLength = 10.5;
var secondPencilLength = 8.5;
console.log("Is first pencil longer than second pencil? I predict True!");
console.log(firstPencilLength > secondPencilLength);
var fruit3 = "apple";
var fruit4 = "banana";
console.log("Is fruit1 not equal to fruit2? I predict True.");
console.log(fruit3 != fruit4);
var str1 = "hi";
var str2 = "world";
console.log("Is str1 not equal to str2? I predict True.");
console.log(str1 != str2);
var weightBall1 = 1.5;
var weightBall2 = 2;
console.log("Is weight of ball 2 lighter than weight of ball 1? I predict False.");
console.log(weightBall2 < weightBall1);
var str3 = "hello";
var str4 = "jawad";
console.log("Is str3 equal to str4? I predict False.");
console.log(str1 == str2);
var bool1 = true;
var bool2 = true;
console.log("Is bool1 not equals to bool2? I predict False.");
console.log(bool1 != bool2);
var fruit6 = "pear";
var fruit7 = "blueberry";
console.log("Is fruit6 less than fruit7? I predict False.");
console.log(fruit6 < fruit7);
var list1 = ["a", "b", "c", "d"];
var list2 = ["g", "h", "i", "j", "k", "l"];
console.log("Is list1 length greater than list2 length? I predict False.");
console.log(list1.length > list2.length);
